import type { Product, Category } from "@/lib/types";

/**
 * Placeholder data used when database is not yet configured.
 * This lets the UI render fully even before the user has run
 * the SQL migration on Supabase.
 */

export const placeholderCategories: Category[] = [
  {
    id: "cat-1",
    name: "Panjabi Collection",
    slug: "panjabi-collection",
    description: "Premium panjabis crafted with the finest fabrics",
    image: null,
    icon: null,
    parent_id: null,
    order: 1,
    is_featured: true,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-2",
    name: "Shirts",
    slug: "shirts",
    description: "Formal and casual shirts for every occasion",
    image: null,
    icon: null,
    parent_id: null,
    order: 2,
    is_featured: true,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-3",
    name: "T-Shirts",
    slug: "t-shirts",
    description: "Comfortable and stylish t-shirts",
    image: null,
    icon: null,
    parent_id: null,
    order: 3,
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-4",
    name: "Polo Shirts",
    slug: "polo-shirts",
    description: "Classic polo shirts for a refined look",
    image: null,
    icon: null,
    parent_id: null,
    order: 4,
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-5",
    name: "Jeans",
    slug: "jeans",
    description: "Premium denim in various fits and washes",
    image: null,
    icon: null,
    parent_id: null,
    order: 5,
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-6",
    name: "Pants",
    slug: "pants",
    description: "Formal and casual pants",
    image: null,
    icon: null,
    parent_id: null,
    order: 6,
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-7",
    name: "Trousers",
    slug: "trousers",
    description: "Refined trousers for the modern man",
    image: null,
    icon: null,
    parent_id: null,
    order: 7,
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-8",
    name: "Blazers",
    slug: "blazers",
    description: "Elegant blazers for formal occasions",
    image: null,
    icon: null,
    parent_id: null,
    order: 8,
    is_featured: true,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-9",
    name: "Waistcoats",
    slug: "waistcoats",
    description: "Stylish waistcoats to complete your look",
    image: null,
    icon: null,
    parent_id: null,
    order: 9,
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-10",
    name: "Hoodies",
    slug: "hoodies",
    description: "Comfortable hoodies for casual wear",
    image: null,
    icon: null,
    parent_id: null,
    order: 10,
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-11",
    name: "Jackets",
    slug: "jackets",
    description: "Premium jackets for all seasons",
    image: null,
    icon: null,
    parent_id: null,
    order: 11,
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-12",
    name: "Punjabi Pajama",
    slug: "punjabi-pajama",
    description: "Traditional pajamas to pair with your panjabi",
    image: null,
    icon: null,
    parent_id: null,
    order: 12,
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-13",
    name: "Sherwani",
    slug: "sherwani",
    description: "Royal sherwanis for weddings and special occasions",
    image: null,
    icon: null,
    parent_id: null,
    order: 13,
    is_featured: true,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-14",
    name: "Kids Collection",
    slug: "kids-collection",
    description: "Stylish clothing for the little ones",
    image: null,
    icon: null,
    parent_id: null,
    order: 14,
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-15",
    name: "Women Collection",
    slug: "women-collection",
    description: "Elegant fashion for women",
    image: null,
    icon: null,
    parent_id: null,
    order: 15,
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
  {
    id: "cat-16",
    name: "Accessories",
    slug: "accessories",
    description: "Complete your look with premium accessories",
    image: null,
    icon: null,
    parent_id: null,
    order: 16,
    is_featured: false,
    is_active: true,
    seo_title: null,
    seo_description: null,
  },
];

interface PlaceholderProduct extends Product {
  images: string[];
  colors: { name: string; hex_value: string }[];
  sizes: string[];
  brand_name?: string;
  category_name?: string;
  rating?: number;
  review_count?: number;
}

export const placeholderProducts: PlaceholderProduct[] = [
  {
    id: "prod-1",
    name: "Premium Cotton Panjabi — Emerald",
    slug: "premium-cotton-panjabi-emerald",
    sku: "RPH-PAN-001",
    description:
      "Experience luxury with our Premium Cotton Panjabi in deep emerald. Crafted from 100% premium cotton, this panjabi features elegant embroidery on the collar and cuffs. Perfect for special occasions, festive celebrations, or elevating your everyday style. The breathable fabric ensures all-day comfort while maintaining a refined silhouette.",
    short_description: "Premium cotton panjabi with elegant embroidery",
    fabric: "100% Premium Cotton",
    fit: "Regular Fit",
    care: "Machine wash cold, iron at low temperature",
    origin: "Made in Bangladesh",
    brand_id: null,
    category_id: "cat-1",
    price: 2499,
    discount_price: 1999,
    cost_price: null,
    currency: "BDT",
    status: "ACTIVE",
    type: "PHYSICAL",
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: true,
    is_flash_sale: true,
    allow_preorder: false,
    allow_reviews: true,
    allow_returns: true,
    meta_title: null,
    meta_description: null,
    search_keywords: "panjabi, cotton, emerald, premium",
    video: null,
    weight_kg: 0.5,
    published_at: new Date().toISOString(),
    flash_sale_start: null,
    flash_sale_end: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ["#0F5132", "#1A1A1F", "#8B6F47"],
    colors: [
      { name: "Emerald", hex_value: "#0F5132" },
      { name: "Charcoal", hex_value: "#1A1A1F" },
      { name: "Brown", hex_value: "#8B6F47" },
    ],
    sizes: ["38", "40", "42", "44", "46"],
    brand_name: "Rakib Premium",
    category_name: "Panjabi Collection",
    rating: 4.8,
    review_count: 124,
  },
  {
    id: "prod-2",
    name: "Royal Silk Sherwani — Ivory Gold",
    slug: "royal-silk-sherwani-ivory-gold",
    sku: "RPH-SHW-001",
    description:
      "Make your special day unforgettable with our Royal Silk Sherwani. Crafted from premium silk fabric in ivory with intricate gold zari embroidery. Features traditional motifs on the collar, chest, and sleeves. Includes matching churidar pajama. The perfect choice for grooms, weddings, and grand celebrations.",
    short_description: "Royal silk sherwani with gold embroidery",
    fabric: "Premium Silk with Zari Work",
    fit: "Tailored Fit",
    care: "Dry clean only",
    origin: "Handcrafted in Bangladesh",
    brand_id: null,
    category_id: "cat-13",
    price: 12999,
    discount_price: 9999,
    cost_price: null,
    currency: "BDT",
    status: "ACTIVE",
    type: "PHYSICAL",
    is_featured: true,
    is_best_seller: false,
    is_new_arrival: true,
    is_flash_sale: false,
    allow_preorder: true,
    allow_reviews: true,
    allow_returns: true,
    meta_title: null,
    meta_description: null,
    search_keywords: "sherwani, silk, ivory, gold, wedding, groom",
    video: null,
    weight_kg: 1.2,
    published_at: new Date().toISOString(),
    flash_sale_start: null,
    flash_sale_end: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ["#F5F1E8", "#B8860B", "#1A1A1F"],
    colors: [
      { name: "Ivory Gold", hex_value: "#F5F1E8" },
      { name: "Royal Maroon", hex_value: "#800020" },
    ],
    sizes: ["38", "40", "42", "44", "46"],
    brand_name: "Rakib Royal",
    category_name: "Sherwani",
    rating: 4.9,
    review_count: 87,
  },
  {
    id: "prod-3",
    name: "Linen Casual Shirt — Sand",
    slug: "linen-casual-shirt-sand",
    sku: "RPH-SHT-001",
    description:
      "Stay cool and stylish with our Linen Casual Shirt in sand color. Made from 100% pure linen, this shirt is perfect for Bangladesh's warm climate. Features a modern collar, button-down front, and relaxed fit. Versatile enough for both casual and semi-formal occasions.",
    short_description: "Breathable linen casual shirt",
    fabric: "100% Pure Linen",
    fit: "Relaxed Fit",
    care: "Machine wash cold, hang dry",
    origin: "Made in Bangladesh",
    brand_id: null,
    category_id: "cat-2",
    price: 1499,
    discount_price: 1199,
    cost_price: null,
    currency: "BDT",
    status: "ACTIVE",
    type: "PHYSICAL",
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    is_flash_sale: false,
    allow_preorder: false,
    allow_reviews: true,
    allow_returns: true,
    meta_title: null,
    meta_description: null,
    search_keywords: "shirt, linen, casual, sand",
    video: null,
    weight_kg: 0.3,
    published_at: new Date().toISOString(),
    flash_sale_start: null,
    flash_sale_end: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ["#D2B48C", "#FFFFFF", "#1A1A1F"],
    colors: [
      { name: "Sand", hex_value: "#D2B48C" },
      { name: "White", hex_value: "#FFFFFF" },
      { name: "Charcoal", hex_value: "#1A1A1F" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    brand_name: "Rakib Essentials",
    category_name: "Shirts",
    rating: 4.7,
    review_count: 203,
  },
  {
    id: "prod-4",
    name: "Tailored Wool Blazer — Charcoal",
    slug: "tailored-wool-blazer-charcoal",
    sku: "RPH-BLZ-001",
    description:
      "Elevate your formal wardrobe with our Tailored Wool Blazer in charcoal. Crafted from premium wool blend, this blazer features a modern slim-fit silhouette, notch lapel, and two-button closure. Perfect for business meetings, formal events, or smart-casual outings.",
    short_description: "Premium tailored wool blazer",
    fabric: "Wool Blend (70% Wool, 30% Polyester)",
    fit: "Slim Fit",
    care: "Dry clean only",
    origin: "Made in Bangladesh",
    brand_id: null,
    category_id: "cat-8",
    price: 5999,
    discount_price: 4499,
    cost_price: null,
    currency: "BDT",
    status: "ACTIVE",
    type: "PHYSICAL",
    is_featured: true,
    is_best_seller: false,
    is_new_arrival: true,
    is_flash_sale: true,
    allow_preorder: false,
    allow_reviews: true,
    allow_returns: true,
    meta_title: null,
    meta_description: null,
    search_keywords: "blazer, wool, charcoal, formal",
    video: null,
    weight_kg: 0.8,
    published_at: new Date().toISOString(),
    flash_sale_start: null,
    flash_sale_end: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ["#1A1A1F", "#36454F", "#8B6F47"],
    colors: [
      { name: "Charcoal", hex_value: "#1A1A1F" },
      { name: "Navy", hex_value: "#1A237E" },
      { name: "Camel", hex_value: "#8B6F47" },
    ],
    sizes: ["38", "40", "42", "44", "46"],
    brand_name: "Rakib Formal",
    category_name: "Blazers",
    rating: 4.8,
    review_count: 156,
  },
  {
    id: "prod-5",
    name: "Premium Oxford Shirt — White",
    slug: "premium-oxford-shirt-white",
    sku: "RPH-SHT-002",
    description:
      "A timeless classic — our Premium Oxford Shirt in white. Made from 100% cotton Oxford weave, this shirt is a wardrobe essential. Features a button-down collar, chest pocket, and regular fit. Perfect for both formal and casual wear.",
    short_description: "Classic oxford cotton shirt",
    fabric: "100% Cotton Oxford",
    fit: "Regular Fit",
    care: "Machine wash warm, iron medium",
    origin: "Made in Bangladesh",
    brand_id: null,
    category_id: "cat-2",
    price: 1799,
    discount_price: 1399,
    cost_price: null,
    currency: "BDT",
    status: "ACTIVE",
    type: "PHYSICAL",
    is_featured: false,
    is_best_seller: true,
    is_new_arrival: false,
    is_flash_sale: false,
    allow_preorder: false,
    allow_reviews: true,
    allow_returns: true,
    meta_title: null,
    meta_description: null,
    search_keywords: "shirt, oxford, white, formal",
    video: null,
    weight_kg: 0.35,
    published_at: new Date().toISOString(),
    flash_sale_start: null,
    flash_sale_end: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ["#FFFFFF", "#F5F5F0", "#1A1A1F"],
    colors: [
      { name: "White", hex_value: "#FFFFFF" },
      { name: "Sky Blue", hex_value: "#87CEEB" },
      { name: "Charcoal", hex_value: "#1A1A1F" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    brand_name: "Rakib Essentials",
    category_name: "Shirts",
    rating: 4.6,
    review_count: 178,
  },
  {
    id: "prod-6",
    name: "Embroidered Kurta Pajama — Maroon",
    slug: "embroidered-kurta-pajama-maroon",
    sku: "RPH-PAN-002",
    description:
      "Traditional elegance meets modern style with our Embroidered Kurta Pajama in maroon. Features intricate thread embroidery on the placket and cuffs. Made from comfortable cotton blend fabric. Includes matching pajama. Perfect for Eid, family gatherings, and festive occasions.",
    short_description: "Embroidered kurta with pajama set",
    fabric: "Cotton Blend (60% Cotton, 40% Polyester)",
    fit: "Regular Fit",
    care: "Machine wash cold, iron medium",
    origin: "Made in Bangladesh",
    brand_id: null,
    category_id: "cat-1",
    price: 3499,
    discount_price: 2799,
    cost_price: null,
    currency: "BDT",
    status: "ACTIVE",
    type: "PHYSICAL",
    is_featured: true,
    is_best_seller: false,
    is_new_arrival: true,
    is_flash_sale: false,
    allow_preorder: false,
    allow_reviews: true,
    allow_returns: true,
    meta_title: null,
    meta_description: null,
    search_keywords: "kurta, pajama, maroon, embroidered, eid",
    video: null,
    weight_kg: 0.6,
    published_at: new Date().toISOString(),
    flash_sale_start: null,
    flash_sale_end: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ["#800020", "#1A1A1F", "#8B6F47"],
    colors: [
      { name: "Maroon", hex_value: "#800020" },
      { name: "Black", hex_value: "#1A1A1F" },
      { name: "Olive", hex_value: "#556B2F" },
    ],
    sizes: ["38", "40", "42", "44", "46"],
    brand_name: "Rakib Premium",
    category_name: "Panjabi Collection",
    rating: 4.9,
    review_count: 94,
  },
  {
    id: "prod-7",
    name: "Slim Fit Jeans — Dark Indigo",
    slug: "slim-fit-jeans-dark-indigo",
    sku: "RPH-JNS-001",
    description:
      "Premium denim with a modern slim fit. Our Slim Fit Jeans in dark indigo feature a comfortable stretch fabric, five-pocket design, and a versatile wash that goes with everything. Perfect for casual wear or dressing up with a shirt.",
    short_description: "Stretch denim slim fit jeans",
    fabric: "98% Cotton, 2% Elastane",
    fit: "Slim Fit",
    care: "Machine wash cold, tumble dry low",
    origin: "Made in Bangladesh",
    brand_id: null,
    category_id: "cat-5",
    price: 2299,
    discount_price: 1799,
    cost_price: null,
    currency: "BDT",
    status: "ACTIVE",
    type: "PHYSICAL",
    is_featured: false,
    is_best_seller: true,
    is_new_arrival: false,
    is_flash_sale: false,
    allow_preorder: false,
    allow_reviews: true,
    allow_returns: true,
    meta_title: null,
    meta_description: null,
    search_keywords: "jeans, denim, slim, indigo",
    video: null,
    weight_kg: 0.7,
    published_at: new Date().toISOString(),
    flash_sale_start: null,
    flash_sale_end: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ["#1A237E", "#0D1117", "#8B6F47"],
    colors: [
      { name: "Dark Indigo", hex_value: "#1A237E" },
      { name: "Black", hex_value: "#0D1117" },
      { name: "Stone Wash", hex_value: "#8B6F47" },
    ],
    sizes: ["30", "32", "34", "36", "38"],
    brand_name: "Rakib Denim",
    category_name: "Jeans",
    rating: 4.7,
    review_count: 256,
  },
  {
    id: "prod-8",
    name: "Quilted Winter Jacket — Olive",
    slug: "quilted-winter-jacket-olive",
    sku: "RPH-JKT-001",
    description:
      "Stay warm in style with our Quilted Winter Jacket in olive. Features a lightweight quilted design, full-zip closure, and two side pockets. The water-resistant outer shell and insulated lining provide excellent warmth without bulk. Perfect for winter weather.",
    short_description: "Lightweight quilted winter jacket",
    fabric: "Polyester Outer with Polyester Fill",
    fit: "Regular Fit",
    care: "Machine wash cold, hang dry",
    origin: "Made in Bangladesh",
    brand_id: null,
    category_id: "cat-11",
    price: 3999,
    discount_price: 3199,
    cost_price: null,
    currency: "BDT",
    status: "ACTIVE",
    type: "PHYSICAL",
    is_featured: false,
    is_best_seller: false,
    is_new_arrival: true,
    is_flash_sale: false,
    allow_preorder: false,
    allow_reviews: true,
    allow_returns: true,
    meta_title: null,
    meta_description: null,
    search_keywords: "jacket, winter, quilted, olive",
    video: null,
    weight_kg: 0.6,
    published_at: new Date().toISOString(),
    flash_sale_start: null,
    flash_sale_end: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ["#556B2F", "#1A1A1F", "#8B6F47"],
    colors: [
      { name: "Olive", hex_value: "#556B2F" },
      { name: "Black", hex_value: "#1A1A1F" },
      { name: "Navy", hex_value: "#1A237E" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    brand_name: "Rakib Outerwear",
    category_name: "Jackets",
    rating: 4.8,
    review_count: 67,
  },
  {
    id: "prod-9",
    name: "Cotton Polo Shirt — Navy",
    slug: "cotton-polo-shirt-navy",
    sku: "RPH-PLO-001",
    description:
      "A versatile wardrobe staple — our Cotton Polo Shirt in navy. Made from premium pique cotton, this polo features a classic two-button placket, ribbed collar and cuffs, and a tailored fit. Perfect for smart-casual occasions.",
    short_description: "Premium pique cotton polo shirt",
    fabric: "100% Pique Cotton",
    fit: "Tailored Fit",
    care: "Machine wash cold, tumble dry low",
    origin: "Made in Bangladesh",
    brand_id: null,
    category_id: "cat-4",
    price: 1199,
    discount_price: 899,
    cost_price: null,
    currency: "BDT",
    status: "ACTIVE",
    type: "PHYSICAL",
    is_featured: false,
    is_best_seller: true,
    is_new_arrival: false,
    is_flash_sale: true,
    allow_preorder: false,
    allow_reviews: true,
    allow_returns: true,
    meta_title: null,
    meta_description: null,
    search_keywords: "polo, shirt, cotton, navy",
    video: null,
    weight_kg: 0.25,
    published_at: new Date().toISOString(),
    flash_sale_start: null,
    flash_sale_end: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ["#1A237E", "#FFFFFF", "#1A1A1F"],
    colors: [
      { name: "Navy", hex_value: "#1A237E" },
      { name: "White", hex_value: "#FFFFFF" },
      { name: "Black", hex_value: "#1A1A1F" },
      { name: "Maroon", hex_value: "#800020" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    brand_name: "Rakib Essentials",
    category_name: "Polo Shirts",
    rating: 4.6,
    review_count: 142,
  },
  {
    id: "prod-10",
    name: "Premium T-Shirt — Heather Grey",
    slug: "premium-t-shirt-heather-grey",
    sku: "RPH-TST-001",
    description:
      "Soft, comfortable, and stylish — our Premium T-Shirt in heather grey. Made from ringspun cotton with a modern fit. Features a ribbed crew neckline and short sleeves. An everyday essential that pairs with everything.",
    short_description: "Soft ringspun cotton t-shirt",
    fabric: "100% Ringspun Cotton",
    fit: "Modern Fit",
    care: "Machine wash cold, tumble dry low",
    origin: "Made in Bangladesh",
    brand_id: null,
    category_id: "cat-3",
    price: 799,
    discount_price: 599,
    cost_price: null,
    currency: "BDT",
    status: "ACTIVE",
    type: "PHYSICAL",
    is_featured: false,
    is_best_seller: true,
    is_new_arrival: false,
    is_flash_sale: false,
    allow_preorder: false,
    allow_reviews: true,
    allow_returns: true,
    meta_title: null,
    meta_description: null,
    search_keywords: "tshirt, t-shirt, cotton, grey",
    video: null,
    weight_kg: 0.2,
    published_at: new Date().toISOString(),
    flash_sale_start: null,
    flash_sale_end: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ["#8B8B8B", "#FFFFFF", "#1A1A1F"],
    colors: [
      { name: "Heather Grey", hex_value: "#8B8B8B" },
      { name: "White", hex_value: "#FFFFFF" },
      { name: "Black", hex_value: "#1A1A1F" },
      { name: "Navy", hex_value: "#1A237E" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    brand_name: "Rakib Essentials",
    category_name: "T-Shirts",
    rating: 4.5,
    review_count: 312,
  },
  {
    id: "prod-11",
    name: "Formal Trousers — Black",
    slug: "formal-trousers-black",
    sku: "RPH-TRS-001",
    description:
      "Sharp and sophisticated — our Formal Trousers in black. Made from a premium poly-wool blend, these trousers feature a flat front, slim leg, and a comfortable waistband. Perfect for office wear, business meetings, and formal events.",
    short_description: "Premium poly-wool formal trousers",
    fabric: "Poly-Wool Blend (65% Polyester, 35% Wool)",
    fit: "Slim Fit",
    care: "Machine wash cold, iron medium",
    origin: "Made in Bangladesh",
    brand_id: null,
    category_id: "cat-7",
    price: 2499,
    discount_price: 1999,
    cost_price: null,
    currency: "BDT",
    status: "ACTIVE",
    type: "PHYSICAL",
    is_featured: false,
    is_best_seller: false,
    is_new_arrival: true,
    is_flash_sale: false,
    allow_preorder: false,
    allow_reviews: true,
    allow_returns: true,
    meta_title: null,
    meta_description: null,
    search_keywords: "trousers, formal, black, pants",
    video: null,
    weight_kg: 0.5,
    published_at: new Date().toISOString(),
    flash_sale_start: null,
    flash_sale_end: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ["#0D1117", "#1A1A1F", "#36454F"],
    colors: [
      { name: "Black", hex_value: "#0D1117" },
      { name: "Charcoal", hex_value: "#1A1A1F" },
      { name: "Navy", hex_value: "#1A237E" },
    ],
    sizes: ["30", "32", "34", "36", "38"],
    brand_name: "Rakib Formal",
    category_name: "Trousers",
    rating: 4.7,
    review_count: 89,
  },
  {
    id: "prod-12",
    name: "Premium Leather Belt — Brown",
    slug: "premium-leather-belt-brown",
    sku: "RPH-ACC-001",
    description:
      "Crafted from genuine leather — our Premium Leather Belt in brown. Features a sleek matte buckle and a timeless design that complements both formal and casual attire. Adjustable length for the perfect fit.",
    short_description: "Genuine leather belt with matte buckle",
    fabric: "Genuine Leather",
    fit: "Adjustable",
    care: "Wipe with damp cloth",
    origin: "Made in Bangladesh",
    brand_id: null,
    category_id: "cat-16",
    price: 1299,
    discount_price: 999,
    cost_price: null,
    currency: "BDT",
    status: "ACTIVE",
    type: "PHYSICAL",
    is_featured: false,
    is_best_seller: true,
    is_new_arrival: false,
    is_flash_sale: false,
    allow_preorder: false,
    allow_reviews: true,
    allow_returns: true,
    meta_title: null,
    meta_description: null,
    search_keywords: "belt, leather, brown, accessory",
    video: null,
    weight_kg: 0.3,
    published_at: new Date().toISOString(),
    flash_sale_start: null,
    flash_sale_end: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: ["#8B6F47", "#1A1A1F"],
    colors: [
      { name: "Brown", hex_value: "#8B6F47" },
      { name: "Black", hex_value: "#1A1A1F" },
    ],
    sizes: ["Free Size"],
    brand_name: "Rakib Accessories",
    category_name: "Accessories",
    rating: 4.8,
    review_count: 178,
  },
];
